# Generated by Django 3.0.5 on 2021-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='tage',
        ),
        migrations.AddField(
            model_name='produit',
            name='jobe_type',
            field=models.CharField(choices=[('telephone', 'telephone'), ('pc portable', 'pc portable')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
