# Generated by Django 3.0.5 on 2021-02-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_auto_20210206_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='jobe_type',
        ),
        migrations.AddField(
            model_name='produit',
            name='Categorie',
            field=models.CharField(choices=[('multimudia', 'multimudia'), ('vhècule', 'vhècule'), ('pour maison et jardain', 'pour maison et jardain'), ('habillement', 'habillement'), ('accèsoire', 'accèsoire')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
