# Generated by Django 3.0.5 on 2021-04-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210205_2323'),
        ('commande', '0002_commande_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_clinet', to='client.Client'),
        ),
    ]
